spring:
  application:
     name: quotes-service
pivotal:
  quotes:
    quotes_url: http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol={symbol}
    quotes_url2: http://globalquotes.xignite.com/v3/xGlobalQuotes.json/GetGlobalDelayedQuote?IdentifierType=Symbol&Identifier={symbol}&_token=DD91EB5927094A87988FF6A492402832
    companies_url: http://dev.markitondemand.com/MODApis/Api/v2/Lookup/json?input={name}
    yahoo_rest_query: https://query.yahooapis.com/v1/public/yql?q=select * from yahoo.finance.quotes where symbol in ('{symbol}')&format={fmt}&env={env}
    yahoo_env: http://datatables.org/alltables.env
security:
  basic:
    enabled: false
